"""Generate the authoritative indicator-availability tables from the registries.

Single source of truth: the `INDICATORS` and `SQL_INDICATORS` dicts in
`scanlang.indicators` / `scanlang.duckdb_sql`. The output files

- ``docs/reference/_indicator_availability_full.md`` (every name)
- ``docs/reference/_indicator_availability.md`` (the dual-engine subset
  the user-facing reference page actually wants to show)

are the inclusion points for the prose reference page; regenerate with:

    uv run python scripts/gen_indicator_availability.py

so hand-maintained counts (e.g. "26 candlestick names", "53 CDL
entries") cannot drift from the implemented catalog.

Probed-only, no live talib / duckdb probe — the table is structural
(arg_spec, required_cols, registry membership), so it works on a
talib-less / duckdb-less interpreter too.

The table emitted:

    | name | arg_spec | required_cols | polars | duckdb | tier (sql) | warm-up (bars) |

where:

- polars = name in INDICATORS (a registered polars builder exists)
- duckdb = name in SQL_INDICATORS (a registered SQL builder exists)
- tier (sql) = "native" / "t_*" / "list CTE" / "two-step window" / "-"
- warm-up (bars) = the live-talib documented warm-up for the function
  (None for indices with no talib equivalent or a per-pattern "0").
  Hand-maintained, but centralized in one place per name (not per page).

The warm-up column is the only column that's not introspected from the
registries — it's a small static lookup; the doc still has a single
source because the table is regenerated by this script.
"""

from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path

from scanlang import INDICATORS as POLARS_REG
from scanlang.duckdb_sql import SQL_INDICATORS as SQL_REG

# SQL tier per name. The native/t_* split is encoded in the duckdb_sql
# module (`_WINDOW` frozenset at the top of duckdb_sql.py) plus a
# hand-list for the two-step-window (`adr`) and the list-CTE multi-output
# functions. Everything else in the `t_*` tier uses the per-partition
# list CTE with unnest. Anything not in this dict defaults to "t_*".
_NATIVE = frozenset(("sma", "rmin", "rmax", "shift"))
_TIER: dict[str, str] = {
    "sma": "native window",
    "rmin": "native window",
    "rmax": "native window",
    "shift": "native window",
    "adr": "two-step window",
    "rs_ratio": "list CTE (two-stage)",
    "rs_momentum": "list CTE (two-stage)",
    "macd": "list CTE (struct-narrowed)",
    "bbands_upper": "list CTE (struct-narrowed)",
    "bbands_lower": "list CTE (struct-narrowed)",
    "aroon": "list CTE (struct-narrowed)",
    "stoch_k": "list CTE (struct-narrowed)",
    "stoch_d": "list CTE (struct-narrowed)",
}

# Live-talib warm-up (null bars per symbol) for the documented
# function; None where the indicator has no talib equivalent
# (e.g. `ad` which is a cumulative sum, `rs_ratio`/`rs_momentum`
# which are z-scores), or a per-pattern value for the candlestick set
# (the cdlengulfing / cdlhikkake / cdlkicking families emit from bar 0
# so 0 is the right pin).
#
# Sources: TA-Lib 0.7.1 reference manual (lookback = unstable_period);
# the candlestick patterns have lookback 1 (2 bars). The dual-engine
# polars seam normalizes NaN to None at the same point, so the bar
# count matches the SQL engine's t_* warm-up.
_WARMUP: dict[str, int | None] = {
    "sma": None,  # the window n itself, not a fixed value
    "ema": None,
    "rsi": None,
    "atr": None,
    "adr": None,
    "roc": None,
    "natr": None,
    "slope": None,
    "rmin": None,
    "rmax": None,
    "shift": None,
    "rs_ratio": None,  # trailing z over n smoothed values
    "rs_momentum": None,
    "wma": None,
    "dema": None,
    "tema": None,
    "trima": None,
    "mom": None,
    "midprice": None,
    "cci": None,
    "willr": None,
    "trange": 1,  # bar 0's null pc propagates; bar 1 is the first real value
    "ad": 0,  # cumulative, no warm-up
    "kama": None,
    "macd": 33,  # 12 + 26 - 1 + 9 - 1 (slow + signal - 2, see talib)
    "bbands_upper": None,
    "bbands_lower": None,
    "adx": 27,  # 2n - 1 for n=14
    "aroon": None,
    "ht_trendline": 63,  # dominant cycle, talib documented
    "stoch_k": None,
    "stoch_d": None,
}


def _row(name: str) -> tuple[str, str, str, str, str, str, str]:
    """One row of the availability table for ``name``."""
    in_pl = name in POLARS_REG
    in_sql = name in SQL_REG
    if in_pl and in_sql:
        arg_spec, _, required = POLARS_REG[name]
        # both registries mirror arg_spec/required_cols 1:1 (asserted by
        # tests/test_duckdb_sql.py::test_sql_registry_superset_of_indicators)
        assert SQL_REG[name][0] == arg_spec
        assert SQL_REG[name][2] == required
    elif in_sql:
        arg_spec, _, required = SQL_REG[name]
    else:
        arg_spec, _, required = POLARS_REG[name]
    polars = "yes" if in_pl else "—"
    duckdb = "yes" if in_sql else "—"
    tier = _TIER.get(name, "t_*" if in_sql else "—")
    warm = _WARMUP.get(name)
    warmup = "—" if warm is None else str(warm)
    return (
        f"`{name}`",
        ", ".join(arg_spec) or "()",
        ", ".join(required) or "—",
        polars,
        duckdb,
        tier,
        warmup,
    )


def _emit(include_dual_only: bool = False) -> str:
    """Return the rendered markdown table body (no header)."""
    names = sorted(set(POLARS_REG) | set(SQL_REG))
    if include_dual_only:
        names = [n for n in names if n in POLARS_REG and n in SQL_REG]
    rows = [_row(n) for n in names]
    # column widths
    cols = list(zip(*rows, strict=True)) if rows else (("name",) * 7,)
    widths = [max(len(s) for s in col) for col in cols]
    out = io.StringIO()
    out.write("| " + " | ".join(c.ljust(w) for c, w in zip(
        ("Indicator", "arg_spec", "required_cols", "polars", "duckdb", "tier (sql)", "warm-up (bars)"),
        widths, strict=True)) + " |\n")
    out.write("| " + " | ".join("---" for _ in widths) + " |\n")
    for row in rows:
        out.write("| " + " | ".join(c.ljust(w) for c, w in zip(row, widths, strict=True)) + " |\n")
    return out.getvalue()


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--out-full",
        type=Path,
        default=Path("docs/reference/_indicator_availability_full.md"),
        help="Full-catalog output (every name).",
    )
    p.add_argument(
        "--out-dual",
        type=Path,
        default=Path("docs/reference/_indicator_availability.md"),
        help="Dual-engine output (the names present in BOTH registries).",
    )
    p.add_argument(
        "--stdout",
        action="store_true",
        help="Print the dual-engine table to stdout (used by the test gate).",
    )
    args = p.parse_args()

    header = (
        "<!-- This file is generated by scripts/gen_indicator_availability.py. "
        "Do not edit by hand. Regenerate after any registry change with:\n"
        "     uv run python scripts/gen_indicator_availability.py\n"
        "-->\n\n"
    )
    full_body = _emit(include_dual_only=False)
    dual_body = _emit(include_dual_only=True)
    if args.stdout:
        sys.stdout.write(header + dual_body)
        return 0
    args.out_full.write_text(header + full_body)
    args.out_dual.write_text(header + dual_body)
    full_n = len(full_body.splitlines()) - 2
    dual_n = len(dual_body.splitlines()) - 2
    print(f"wrote {args.out_full} ({full_n} names)")
    print(f"wrote {args.out_dual} ({dual_n} names)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
